# Generated by Django 4.2 on 2023-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalInternetRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('proposals_url', models.URLField(verbose_name='Proposals URL')),
            ],
            options={
                'verbose_name': 'Regional Internet Registry',
                'verbose_name_plural': 'Regional Internet Registries',
            },
        ),
    ]
