# Generated by Django 4.2 on 2023-04-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalinternetregistry',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='PolicyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25, verbose_name='Identifier')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('state', models.CharField(max_length=25, verbose_name='State')),
                ('url', models.URLField(verbose_name='URL')),
                ('rir', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proposals.regionalinternetregistry', verbose_name='RIR')),
            ],
            options={
                'verbose_name': 'Policy Proposal',
                'verbose_name_plural': 'Policy Proposals',
            },
        ),
    ]
