# Generated by Django 4.2 on 2023-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_policyproposal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalinternetregistry',
            name='html_container',
            field=models.CharField(default='', help_text='XPath to the HTML element that contains all proposals', max_length=100, verbose_name='HTML Container'),
            preserve_default=False,
        ),
    ]
