# Generated by Django 4.2 on 2023-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_regionalinternetregistry_html_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalinternetregistry',
            name='html_container',
            field=models.CharField(blank=True, help_text='XPath to the HTML element that contains all proposals', max_length=100, verbose_name='HTML Container'),
        ),
    ]
