# Generated by Django 4.2 on 2023-04-07 13:10

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_alter_regionalinternetregistry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalinternetregistry',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
