# Generated by Django 4.2 on 2023-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_regionalinternetregistry_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalinternetregistry',
            name='html_container',
        ),
        migrations.AddField(
            model_name='regionalinternetregistry',
            name='proposal_selector',
            field=models.CharField(blank=True, help_text='CSS selector that selects one proposal per match', max_length=100, verbose_name='Proposal selector'),
        ),
    ]
