# Generated by Django 4.2 on 2023-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_remove_regionalinternetregistry_html_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalinternetregistry',
            name='identifier_selector',
            field=models.CharField(blank=True, help_text='CSS selector that selects the title of one proposal', max_length=100, verbose_name='Identifier selector'),
        ),
    ]
