# Generated by Django 4.2 on 2023-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_alter_regionalinternetregistry_url_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproposal',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
    ]
