# Generated by Django 4.2 on 2023-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_policyproposal_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyproposal',
            name='last_update',
        ),
        migrations.AddField(
            model_name='policyproposal',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Last change'),
        ),
    ]
