# Generated by Django 4.2 on 2023-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_remove_policyproposal_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalinternetregistry',
            name='date_selector',
            field=models.CharField(blank=True, help_text='CSS selector that selects the last modified date of one proposal', max_length=100, verbose_name='Date selector'),
        ),
        migrations.AlterField(
            model_name='policyproposal',
            name='last_change',
            field=models.DateTimeField(editable=False, verbose_name='Last change'),
        ),
    ]
