# Generated by Django 4.2 on 2023-04-08 16:43

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_regionalinternetregistry_date_selector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalinternetregistry',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='Time zone'),
        ),
    ]
