# Generated by Django 4.2 on 2023-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_regionalinternetregistry_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalinternetregistry',
            name='date_order',
            field=models.CharField(choices=[('DMY', 'DMY'), ('MDY', 'MDY'), ('YMD', 'YMD')], default='DMY', max_length=3, verbose_name='Date order'),
        ),
    ]
